spring.application.name=CasoPractico1

server.port=47

spring.datasource.url=jdbc:mysql://localhost:3306/gimnasio_fitness
spring.datasource.username=usuario_caso_practico_01
spring.datasource.password=123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false